USE MASTER;
GO
DROP DATABASE IF EXISTS TAPCHI;
GO
CREATE DATABASE TAPCHI;
GO
USE TAPCHI;
GO
CREATE TABLE BAIBAO (
    MABAIBAO        CHAR(10)        PRIMARY KEY CHECK(ISNUMERIC(MABAIBAO) = 1),
    TIEUDE          VARCHAR(50)     ,
    TOMTAT          TEXT            ,
    FILEBAIBAO      VARCHAR(200)    ,
    NGAYGOI         DATE            
);

CREATE TABLE NGHIENCUU (
    MABAIBAO        CHAR(10)        PRIMARY KEY,
    CHIEUDAI        INTEGER         NOT NULL CHECK (10 <= CHIEUDAI AND CHIEUDAI <= 20),
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PHANBIENSACH (
    MABAIBAO        CHAR(10)        PRIMARY KEY,
    CHIEUDAI        INTEGER         NOT NULL CHECK (3 <= CHIEUDAI AND CHIEUDAI <= 6),
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TONGQUAN (
    MABAIBAO        CHAR(10)        PRIMARY KEY,
    CHIEUDAI        INTEGER         NOT NULL CHECK (3 <= CHIEUDAI AND CHIEUDAI <= 10),
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SACH (
    ISBN            CHAR(12)        PRIMARY KEY CHECK (ISNUMERIC(ISBN) = 1),
    SOTRANG         INTEGER         ,
    NAMXUATBAN      INTEGER         ,
    NHAXUATBAN      VARCHAR(50)     ,
    TENSACH         VARCHAR(50)
);

CREATE TABLE BAIBAOXUATBAN (
    DOI             VARCHAR(50)     PRIMARY KEY,
    NHAXUATBAN      VARCHAR(50)     ,
    DANGXUATBAN     VARCHAR(11)     CHECK (DANGXUATBAN IN ('TruyenThong', 'OpenAccess')),
    NGAYXUATBAN     DATE
);

CREATE TABLE NHAKHOAHOC (
    SSN             CHAR(9)         PRIMARY KEY CHECK(ISNUMERIC(SSN) = 1),
    HO              VARCHAR(50)     ,
    TEN             VARCHAR(50)     ,
    DIACHI          VARCHAR(200)    ,
    COQUANCONGTAC   VARCHAR(200)    ,
    NGHE            VARCHAR(50)     ,
    DIENTHOAI       VARCHAR(12)     CHECK(ISNUMERIC(DIENTHOAI) = 1)
);

CREATE TABLE TACGIA(
    SSN             CHAR(9)         PRIMARY KEY,
    EMAIL           VARCHAR(200)    ,
    FOREIGN KEY (SSN) REFERENCES NHAKHOAHOC (SSN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PHANBIEN(
    SSN             CHAR(9)         PRIMARY KEY,
    EMAILCANHAN     VARCHAR(200)    ,
    EMAILCOQUAN     VARCHAR(200)    ,
    TRINHDO         VARCHAR(200)    ,
    CHUYENMON       VARCHAR(200)    ,
    NGAYCONGTAC     DATE            ,
    FOREIGN KEY (SSN) REFERENCES NHAKHOAHOC (SSN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BIENTAP(
    SSN             CHAR(9)         PRIMARY KEY,
    EMAIL           VARCHAR(200)    ,
    FOREIGN KEY (SSN) REFERENCES NHAKHOAHOC (SSN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TIEUCHIDANHGIA(
    MATIEUCHI       INTEGER         PRIMARY KEY,
    NOIDUNG         VARCHAR(200)   
);

CREATE TABLE BAIPHANBIEN (
    MABAIBAO        CHAR(10)        ,
    BIENTAPSSN      CHAR(9)         ,
    GHICHUBIENTAP   TEXT            ,
    GHICHUTACGIA    TEXT            ,
    NOIDUNG         TEXT            ,
    PRIMARY KEY (MABAIBAO, BIENTAPSSN),
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BIENTAPSSN) REFERENCES BIENTAP (SSN) ON DELETE CASCADE ON UPDATE CASCADE           
);

CREATE TABLE MUCDANHGIA (
    MATIEUCHI       INTEGER         PRIMARY KEY,
    MOTA            VARCHAR(200)    ,
    DIEM            INTEGER         ,
    FOREIGN KEY (MATIEUCHI) REFERENCES TIEUCHIDANHGIA (MATIEUCHI) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE BAIBAOXUATBAN
ADD MABAIBAO        CHAR(10)        NOT NULL UNIQUE;
ALTER TABLE BAIBAOXUATBAN
ADD FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE;  

ALTER TABLE BAIBAO
ADD TGLLSSN         CHAR(9)         NOT NULL UNIQUE;
ALTER TABLE BAIBAO
ADD FOREIGN KEY (TGLLSSN) REFERENCES TACGIA (SSN); --MISSING CASCADE ACTION

ALTER TABLE BAIBAO
ADD BIENTAPSSN      CHAR(9)         NOT NULL UNIQUE,
    TRANGTHAI       VARCHAR(20)     CHECK (TRANGTHAI IN ('PhanBien', 'PhanHoiPhanBien', 'HoanTatPhanBien', 'XuatBan', 'DaDang')),
    NOIDUNGPHANBIEN VARCHAR(200)    ,
    NGAYTHONGBAO    DATE            ,
    CHITIETKHAC     VARCHAR(200)    ;
ALTER TABLE BAIBAO
ADD FOREIGN KEY (BIENTAPSSN) REFERENCES BIENTAP (SSN); --MISSING CASCADE ACTION

ALTER TABLE PHANBIENSACH
ADD ISBN            CHAR(12)        NOT NULL UNIQUE;
ALTER TABLE PHANBIENSACH
ADD FOREIGN KEY (ISBN) REFERENCES SACH (ISBN) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE LATACGIA (
    TACGIASSN       CHAR(9)         ,
    MABAIBAO        CHAR(10)        ,
    PRIMARY KEY (TACGIASSN, MABAIBAO),
    FOREIGN KEY (TACGIASSN) REFERENCES TACGIA(SSN) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO(MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PHANCONG (
    PHANBIENSSN     CHAR(9)         ,
    MABAIBAO        CHAR(10)        ,
    BIENTAPSSN      CHAR(9)         NOT NULL UNIQUE,
    NGAYPHANCONG    DATE            ,
    HANGOI          DATE            ,
    KETQUA          VARCHAR(50)     ,
    PRIMARY KEY (PHANBIENSSN, MABAIBAO),
    FOREIGN KEY (PHANBIENSSN) REFERENCES PHANBIEN (SSN) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BIENTAPSSN) REFERENCES BIENTAP (SSN), --MISSING CASCADE ACTION
    CHECK (HANGOI >= NGAYPHANCONG)
);

CREATE TABLE COTIEUCHI (
    MABAIBAO        CHAR(10)        ,
    BIENTAPSSN      CHAR(9)         ,
    MATIEUCHI       INTEGER         ,
    KETQUA          INTEGER         ,
    PRIMARY KEY (MABAIBAO, BIENTAPSSN, MATIEUCHI),
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BIENTAPSSN) REFERENCES BIENTAP (SSN) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MATIEUCHI) REFERENCES TIEUCHIDANHGIA (MATIEUCHI) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TUKHOA (
    MABAIBAO        CHAR(10)        ,
    TUKHOA          VARCHAR(50)     ,
    PRIMARY KEY (MABAIBAO, TUKHOA),
    FOREIGN KEY (MABAIBAO) REFERENCES BAIBAO (MABAIBAO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TACGIASACH (
    ISBN            CHAR(12)        ,
    TACGIA          VARCHAR(100)    ,
    PRIMARY KEY (ISBN, TACGIA),
    FOREIGN KEY (ISBN) REFERENCES SACH (ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);